merchtrack/app/urls.py
from django.conf import settings
from django.views.static import serve
from django.urls import path,re_path, include
from . import views
from .view import product, order, customer, report, collection, fulfillment

urlpatterns = [
    # Customers
    path("", views.home, name='home'),
    path("about-us/", views.aboutUs, name='aboutUs'),
    path("contact-us/", views.contactUs, name='contactUs'),
    path("order-entry/", views.orderEntry, name='order-entry'),
    path('registration/', views.register, name='registration'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('customer-payment/', collection.customer_payment, name='customer_payment'),
    path('customer-payment/<int:order_id>/', collection.customer_make_payment, name='customer_make_payment'),
    path('survey/<int:order_id>/', views.survey_view, name='survey_view'),
    path('survey/thank-you/', views.survey_thank_you, name='survey_thank_you'),

    # Staffs
    path('dashboard/', views.dashboard, name='dashboard'),
    path('messages/', views.cust_messages, name='messages'),
    path('send_reply_email/', views.send_reply_email, name='send_reply_email'),
    path('success/', views.success, name='success'),

    # Product
    path('create-product/', product.create_product, name='create_product'),
    path('products/', product.product_list, name='product_list'),
    path('edit-product/<int:product_id>/', product.edit_product, name='edit_product'),
    path('delete-product/<int:product_id>/', product.delete_product, name='delete_product'),

    # Order-entry
    path('create_order/', order.create_order, name='create_order'),
    path('api/customer_info/', views.customer_info, name='customer_info'),
    path('order_list', order.order_list, name='order_list'),
    path('order_detail/<int:order_id>/', order.order_detail, name='order_detail'),
    path('edit_order/<int:order_id>/', order.edit_order, name='edit_order'),
    path('delete_order/<int:order_id>/', order.delete_order, name='delete_order'),


    # Report
    path('reports/', report.report_index, name='reports'),
    path('reports/orders/', report.order_report, name='order_report'),
    path('reports/products/', report.product_report, name='product_report'),
    path('reports/products/<int:product_id>/', report.product_report, name='product_report'),
    # path('reports/customers/<int:customer_id>/', report.customer_report, name='customer_report'),
    path('reports/customers/', report.customer_report, name='customer_report'),
    path('reports/sales/', report.sales_report, name='sales_report'),
    path('reports/fulfillment/', report.fulfillment_report, name='fulfillment_report'),
    path('api/sales_data/<int:product_id>/', report.sales_data_api, name='sales_data_api'),
    path('reports/survey/', report.survey_report, name='survey_report'),
    path('reports/collections/', report.collections_report, name='collections_report'),
    path('reports/logs/', report.log_report, name='log_report'),

    # Admin
    path('customers/', customer.customer_list, name='customer_list'),
    path('customers/<int:customer_id>/', customer.customer_detail, name='customer_detail'),
    path('customers/edit/<int:customer_id>/', customer.edit_customer, name='edit_customer'),
    path('users/', customer.user_list, name='user_list'),
    path('users/<int:user_id>/manage_groups/', customer.manage_user_groups, name='manage_user_groups'),

    # Collection
    path('collections/', collection.collections_index, name='collections_index'),
    path('collections/<int:order_id>/', collection.collection_detail, name='collection_detail'),


    # Fulfillment
    path('fulfillment/', fulfillment.fulfillment_view, name='fulfillment_view'),



    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^.*$', views.not_found, name='404'),
]

merchtrack/merchtrack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchtrack/app/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.utils.timezone import now
import os

# Create your database models here.

class user_info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    student_id = models.CharField(
        max_length=9, 
        primary_key=True,  # Make student_id the primary key
        unique=True, 
        validators=[RegexValidator(r'^[0-9]{1,9}$', 'Student ID must be numeric and have at most 9 digits.')]
    )
    student_name = models.CharField(max_length=200)
    course = models.CharField(max_length=200)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.student_id

class order_info(models.Model):
    order_date = models.CharField(max_length=200)
    distribution_date = models.CharField(max_length=200)
    order_status = models.CharField(max_length=200)
    payment_method = models.CharField(max_length=200)
    payment_status = models.CharField(max_length=200)

    order_details_id = models.CharField(max_length=200, default='0')
    user_info_id  = models.CharField(max_length=9, default='000000000')
    
class order_details(models.Model):
    order_details_id = models.CharField(max_length=200)
    item_name = models.CharField(max_length=200)
    item_size = models.CharField(max_length=200)
    item_color = models.CharField(max_length=200)
    item_cost = models.CharField(max_length=200)
    item_quantity = models.CharField(max_length=200)

class contact_us(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    message = models.TextField(max_length=200)
    created_at = models.DateTimeField(default=now) 



# NEW DATA

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, default=999)
    phone = models.CharField(max_length=15)
    course = models.CharField(max_length=200)

    class Meta:
        db_table = 'customer'
        constraints = [
            models.UniqueConstraint(fields=['user'], name='unique_customer_id')
        ]
        indexes = [
            models.Index(fields=['user'], name='customer_id_idx')
        ]

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

class Product(models.Model):
    productId = models.AutoField(primary_key=True)
    productImage = models.CharField(max_length=500, blank=True, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.CharField(max_length=100)
    available = models.BooleanField(default=True)

    class Meta:
        db_table = 'product'
        constraints = [
            models.UniqueConstraint(fields=['productId'], name='unique_product_id')
        ]
        indexes = [
            models.Index(fields=['productId'], name='product_id_idx')
        ]

    def get_image(self):
        if 'drive.google.com' in self.productImage:
            file_id = self.productImage.split('/d/')[1].split('/')[0]
            return f"https://drive.google.com/thumbnail?id={file_id}&sz=w500"
        return f"https://drive.google.com/thumbnail?id={self.productImage}&sz=w500" 

    def delete(self, *args, **kwargs):
        super(Product, self).delete(*args, **kwargs)

class Order(models.Model):
    orderId = models.AutoField(primary_key=True)
    customerId = models.ForeignKey(Customer, on_delete=models.CASCADE, default=999)
    processedBy = models.ForeignKey(User, on_delete=models.CASCADE, related_name='processed_orders', default=999)
    orderDate = models.DateTimeField(default=now)
    status = models.CharField(max_length=50, default="Pending")
    totalAmount = models.FloatField(max_length=10, default=0)
    discountAmount = models.FloatField(max_length=10, default=0)
    estimatedDeliveryDate = models.DateTimeField()

    class Meta:
        db_table = 'order'
        constraints = [
            models.UniqueConstraint(fields=['orderId'], name='unique_order_id')
        ]
        indexes = [
            models.Index(fields=['orderId'], name='order_id_idx')
        ]

class OrderItem(models.Model):
    orderItemId = models.AutoField(primary_key=True)
    orderId = models.ForeignKey(Order, on_delete=models.CASCADE)
    productId = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    customerNote = models.TextField(blank=True, null=True)
    size = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        db_table = 'order_item'
        constraints = [
            models.UniqueConstraint(fields=['orderItemId'], name='unique_order_item_id')
        ]
        indexes = [
            models.Index(fields=['orderItemId'], name='order_item_id_idx')
        ]

    @property
    def total_price(self):
        return self.quantity * self.price

class Payment(models.Model):
    paymentId = models.AutoField(primary_key=True)
    orderId = models.ForeignKey(Order, on_delete=models.CASCADE)
    customerId = models.ForeignKey(Customer, on_delete=models.CASCADE, default=999)
    processedBy = models.ForeignKey(User, on_delete=models.CASCADE, related_name='processed_payments', default=999)
    paymentDate = models.DateTimeField(default=now)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    paymentMethod = models.CharField(max_length=50)
    paymentStatus = models.CharField(max_length=50, default="For Verification")
    referenceNumber = models.CharField(max_length=100, default="")

    class Meta:
        db_table = 'payment'
        constraints = [
            models.UniqueConstraint(fields=['paymentId'], name='unique_payment_id')
        ]
        indexes = [
            models.Index(fields=['paymentId'], name='payment_id_idx')
        ]

class Inventory(models.Model):
    inventoryId = models.AutoField(primary_key=True)
    productId = models.OneToOneField(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        db_table = 'inventory'
        constraints = [
            models.UniqueConstraint(fields=['inventoryId'], name='unique_inventory_id')
        ]
        indexes = [
            models.Index(fields=['inventoryId'], name='inventory_id_idx')
        ]

class Fulfillment(models.Model):
    fulfillmentId = models.AutoField(primary_key=True)
    orderId = models.OneToOneField(Order, on_delete=models.CASCADE)
    fulfillmentDate = models.DateTimeField(default=now)
    processedBy = models.ForeignKey(User, on_delete=models.CASCADE, related_name='processed_fulfillments', default=999)
    status = models.CharField(max_length=50, default="Pending")


    class Meta:
        db_table = 'fulfillment'
        constraints = [
            models.UniqueConstraint(fields=['fulfillmentId'], name='unique_fulfillment_id')
        ]
        indexes = [
            models.Index(fields=['fulfillmentId'], name='fulfillment_id_idx')
        ]

def get_default_customer():
    customer = Customer.objects.get(pk=999)
    print("Customer: ", customer)
    return customer


class Log(models.Model):
    logId = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    created_date = models.DateTimeField(default=now)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, default=999)
    reason = models.CharField(max_length=255)
    system_text = models.TextField()
    user_text = models.TextField()

    def __str__(self):
        return f"Log for {self.customer.user.username} by {self.created_by.username} on {self.created_date}"
    
    class Meta:
        db_table = 'log'
        constraints = [
            models.UniqueConstraint(fields=['logId'], name='unique_logId_id')
        ]
        indexes = [
            models.Index(fields=['logId'], name='logId_id_idx')
        ]



from django.utils import timezone

class CustomerSatisfactionSurvey(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    submit_date = models.DateTimeField(default=timezone.now)
    question1 = models.IntegerField(choices=[(1, 'Not at all'), (2, 'Somewhat'), (3, 'Very'), (4, 'Completely')])
    question2 = models.IntegerField(choices=[(1, 'Difficult'), (2, 'Neutral'), (3, 'Easy'), (4, 'Very Easy')])
    question3 = models.IntegerField(choices=[(1, 'Not at all'), (2, 'Somewhat'), (3, 'Very'), (4, 'Completely')])
    question4 = models.IntegerField(choices=[(1, 'Unlikely'), (2, 'Neutral'), (3, 'Likely'), (4, 'Very Likely')])
    comments = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'customer_satisfaction_survey'
        constraints = [
            models.UniqueConstraint(fields=['order'], name='unique_order_survey')
        ]

    def __str__(self):
        return f"Survey for Order {self.order.orderId}"

merchtrack/templates/products/create_product.html
{% extends 'base.html' %} {% block title %} Create Product  {% endblock %}
{% load slippers %}

{% block nav %}
    {% back-to-dashboard %}
{% endblock %}

{% block content %}
{% load static %}
<div class='fade-box flex flex-col w-screen h-full bg-[#f3f3f3] overflow-auto p-2'>
    <div class='flex flex-col items-center content-center justify-center w-auto h-auto p-5 m-auto overflow-visible bg-white shadow-xl rounded-xl'>
        <div class='self-start mx-5 w-fit'>
            <div class=' text-[#3BAFE1] text-3xl mb-2 font-bold text-left'>Create a New Product</div>
            <div class='w-full pb-3 mb-2 text-lg italic font-medium border-b'>Easy way to order</div>
        </div>
        <form class='flex flex-row min-w-[50rem]' method="POST" autocomplete='off' enctype="multipart/form-data" >
            <div class='flex flex-col self-start justify-start w-4/6 px-10 my-5' >
                {% csrf_token %}
                <table class='table-auto border-spacing-y-2'>
                    <tr>
                        <td class='py-2 align-top'><label class='mr-2 font-bold' for="{{ form.name.id_for_label }}">{{ form.name.label }}</label></td>
                        <td class='w-full'>{{ form.name }}</td>
                    </tr>
                    
                    <tr>
                        <td class='py-2 align-top'><label class='mb-auto mr-2 font-bold ' for="{{ form.description.id_for_label }}">{{ form.description.label }}</label></td>
                        <td>{{ form.description }}</td>
                    </tr>
                    
                    <tr>
                        <td class='py-2 align-top'><label class='mr-2 font-bold'  for="{{ form.price.id_for_label }}">{{ form.price.label }}</label></td>
                        <td>{{ form.price }}</td>
                    </tr>
                    
                    <tr>
                        <td class='py-2 align-top'><label class='mr-2 font-bold' for="{{ form.category.id_for_label }}">{{ form.category.label }}</label></td>
                        <td>
                            {{ form.category }}
                            <datalist id="category-list">
                                {% for category in form.existing_categories %}
                                    <option value="{{ category }}">{{ category }}</option>
                                {% endfor %}
                            </datalist>
                        </td>
                    </tr>
                </table>

                {% if form.non_field_errors or form.errors %}
                <ul class='w-5/6 p-3 my-5 text-base text-red-700 list-inside bg-red-100 rounded-lg'>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

            </div>
            <div class='flex flex-col h-full p-5 rounded-lg w-72 '>
                <label class='mr-2 font-bold' for="id_productImage">Product Image:</label>
                <div class='flex self-center w-56 h-56 my-5 border rounded-lg bg-slate-200 max-w-56 max-h-56'>
                    <img class='object-cover w-full h-full p-0 rounded-lg' alt='image preview' id='image-prev'  />
                </div>
                <input  class='flex w-full px-1 py-2 file:px-3 file:py-1 file:rounded-full cursor-pointer file:border-0 hover:file:opacity-60 active:file:opacity-85 file:bg-blue-100 file:text-blue-700  my-1 text-sm rounded-lg' type="file" name="productImage" accept="image/*" id="id_productImage" onchange="previewImage(event)">
                <input class='self-end mt-auto w-full text-white bg-[#3BAFE1] border-white text-lg rounded-xl font-Inter font-semibold text-center py-2 px-4 my-2  cursor-pointer active:opacity-100 hover:opacity-[0.5] transition-all' 
                value="Create New Product"
                type="submit"/>
                <a href='{% url 'product_list' %}' class='self-end mt-auto w-full text-black border  text-lg rounded-xl font-Inter font-semibold text-center py-2 px-4 my-5  cursor-pointer active:opacity-100 hover:opacity-[0.5] hover:bg-blue-200 transition-all' >
                    Cancel
                </a>
            </div>


        </form>


    </div>
</div>


<style>

    #image-prev {
        display: none;
        max-width: 300px;
        max-height: 300px;
    }

    p {
        display: flex;
        flex-direction: column;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        align-items: start;
    }
    
    .helptext {
        font-size: 0.8rem;
        color: blue;
        margin-left: 0.5rem;
    }
    
    p label {
        margin-right: 0.5rem;
        font-weight: 700;
    }
    
    ul {
        font-size: 0.8rem;
        list-style: disc;
        margin-left: 1rem;
    }
    
    p input {
        width: 100%;
        border-radius: 25px;
    }
    
    #id_password1, #id_password2 {
        border-radius: 0.5rem;
    }
    
    .errorlist {
        font-size: 0.85rem;
        list-style: none;
        margin: 1rem;
        border-radius: 0.5rem;
        background-color: rgb(254 226 226 );
        color: rgb(185 28 28);
        padding: 0.5rem;
    }

    input[type="text"], input[type="number"], textarea{
        border-radius: 0.5rem;
        width: 100%;

    }

    tr {
        display: grid;
        padding-bottom: 0.25rem; /* Adjust this value for vertical spacing */
    }
    
</style>
<script>
    function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function(){
            var output = document.getElementById('image-prev');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    }
</script>

{% endblock %}

merchtrack/templates/products/edit_product.html
{% extends 'base.html' %} {% block title %} Modify Product  {% endblock %}
{% load slippers %}

{% block nav %}
    {% back-to-dashboard %}
{% endblock %}

{% block content %}
{% load static %}
<div class=' flex flex-col w-screen h-full bg-[#f3f3f3] overflow-auto p-2'>
    <div class='flex flex-col items-center content-center justify-center w-auto h-auto p-5 m-auto overflow-visible bg-white shadow-xl rounded-xl'>
        <div class='self-start mx-5 w-fit'>
            <div class=' text-[#3BAFE1] text-3xl mb-2 font-bold text-left'>Modify Product</div>
            <div class='w-full pb-3 mb-2 text-lg italic font-medium border-b'>Easy way to order</div>
        </div>
        <form class='flex flex-row min-w-[50rem]' method="POST" autocomplete='off' enctype="multipart/form-data" >
            <div class='flex flex-col self-start justify-start w-4/6 px-10 my-5' >
                {% csrf_token %}
                <table class='table-auto border-spacing-y-2'>
                    <div class="inline-flex items-center">
                        <label class="relative -ml-2.5 flex cursor-pointer items-center rounded-full p-3" for="available_checkbox" data-ripple-dark="true">
                            <input
                                type="checkbox"
                                class="before:content[''] peer relative h-5 w-5 cursor-pointer appearance-none rounded-md border border-blue-gray-200 transition-all before:absolute before:top-2/4 before:left-2/4 before:block before:h-12 before:w-12 before:-translate-y-2/4 before:-translate-x-2/4 before:rounded-full before:bg-blue-gray-500 before:opacity-0 before:transition-opacity checked:border-blue-500 checked:bg-blue-500 checked:before:bg-blue-500 hover:before:opacity-10"
                                id="available_checkbox"
                                name="available"
                                {% if product.available %}checked{% endif %}
                            />
                            <span class="absolute text-white transition-opacity opacity-0 pointer-events-none top-2/4 left-2/4 -translate-y-2/4 -translate-x-2/4 peer-checked:opacity-100">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" viewBox="0 0 20 20" fill="currentColor" stroke="currentColor" stroke-width="1">
                                    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
                                </svg>
                            </span>
                        </label>
                        <label class="mt-px font-semibold cursor-pointer select-none" for="available_checkbox">
                            <p class="flex items-center text-base antialiased font-bold leading-normal">Is Product currently available?</p>
                        </label>
                    </div>
                    
                    <tr>
                        <td class='py-2 align-top'><label class='mr-2 font-bold' for="{{ form.name.id_for_label }}">{{ form.name.label }}</label></td>
                        <td class='w-full'>{{ form.name }}</td>
                    </tr>
                    
                    <tr>
                        <td class='py-2 align-top'><label class='mb-auto mr-2 font-bold ' for="{{ form.description.id_for_label }}">{{ form.description.label }}</label></td>
                        <td class='line-clamp-3'>{{ form.description }}</td>
                    </tr>
                    
                    <tr>
                        <td class='py-2 align-top'><label class='mr-2 font-bold'  for="{{ form.price.id_for_label }}">{{ form.price.label }}</label></td>
                        <td>{{ form.price }}</td>
                    </tr>
                    
                    <tr>
                        <td class='py-2 align-top'><label class='mr-2 font-bold' for="{{ form.category.id_for_label }}">{{ form.category.label }}</label></td>
                        <td>
                            <input type="text" name="category" id="{{ form.category.id_for_label }}" list="category-list" value="{{ form.instance.category }}">
                            <datalist id="category-list">
                                {% for category in categories %}
                                    <option value="{{ category }}">{{ category }}</option>
                                {% endfor %}
                            </datalist>
                        </td>
                    </tr>
                    
                </table>

                {% if form.non_field_errors or form.errors %}
                <ul class='w-5/6 p-3 my-5 text-base text-red-700 list-inside bg-red-100 rounded-lg'>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

            </div>
            <div class='flex flex-col h-full p-5 rounded-lg w-72 '>
                <label class='mr-2 font-bold' for="id_productImage">Product Image:</label>
                <div class='flex self-center w-56 h-56 my-5 border rounded-lg bg-slate-200'>
                    {% if product.productImage %}
                    <img src="{{ product.get_image }}" class='z-10 block object-cover w-full h-full p-0 rounded-lg' alt='image preview' id='image-prev' />
                    {% else %}
                    <img class='z-10 block object-cover w-full h-full' alt='image preview' id='image-prev' />
                    {% endif %}
                </div>
                {{ form.productImage }}
                <!-- <input class='flex w-full px-1 py-2 my-1 text-sm rounded-lg cursor-pointer file:px-3 file:py-1 file:rounded-full file:border-0 hover:file:opacity-60 active:file:opacity-85 file:bg-blue-100 file:text-blue-700' type="file" name="productImage" accept="image/*" id="id_productImage" onchange="previewImage(event)"> -->
                <input class='self-end mt-auto w-full text-white bg-[#3BAFE1] font-semibold border-white rounded font-Inter  text-center py-2 px-4 my-2  cursor-pointer active:opacity-100 hover:opacity-[0.5] transition-all' 
                value="Update Product"
                onclick="showModal('confirmationModal')"
                type="submit"/>
                <a href="{% url 'delete_product' product_id=product.productId %}"  class="px-4 py-2 mb-2 font-semibold text-center text-white bg-red-500 rounded cursor-pointer hover:bg-red-700">Delete</a>
                <a href='{% url 'product_list' %}' class='self-end w-full mt-auto text-center btn-secondary' >
                    Cancel
                </a>
            </div>


        </form>


    </div>
</div>
{% modal modal_id='confirmationModal' modal_title='Confirm Modify Product' modal_message='Are you sure you want to modify this product?' modal_warning='This process is not reversible. Actions will be logged for security purposes of the business.' %}

<style>

    #image-prev {
        max-width: 300px;
        max-height: 300px;
    }

    p {
        display: flex;
        flex-direction: column;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        align-items: start;
    }
    
    .helptext {
        font-size: 0.8rem;
        color: blue;
        margin-left: 0.5rem;
    }
    
    p label {
        margin-right: 0.5rem;
        font-weight: 700;
    }
    
    ul {
        font-size: 0.8rem;
        list-style: disc;
        margin-left: 1rem;
    }
    
    p input {
        width: 100%;
        border-radius: 25px;
    }
    
    #id_password1, #id_password2 {
        border-radius: 0.5rem;
    }
    
    .errorlist {
        font-size: 0.85rem;
        list-style: none;
        margin: 1rem;
        border-radius: 0.5rem;
        background-color: rgb(254 226 226 );
        color: rgb(185 28 28);
        padding: 0.5rem;
    }

    input[type="text"], input[type="number"], textarea{
        border-radius: 0.5rem;
        width: 100%;

    }

    tr {
        display: grid;
        padding-bottom: 0.25rem; /* Adjust this value for vertical spacing */
    }
    
</style>
<script>
    function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function(){
            var output = document.getElementById('image-prev');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    }
</script>

{% endblock %}