merchtrack/app/urls.py
from django.conf import settings
from django.views.static import serve
from django.urls import path,re_path, include
from . import views
from .view import product, order, customer, report, collection, fulfillment

urlpatterns = [
    # Customers
    path("", views.home, name='home'),
    path("about-us/", views.aboutUs, name='aboutUs'),
    path("contact-us/", views.contactUs, name='contactUs'),
    path("order-entry/", views.orderEntry, name='order-entry'),
    path('registration/', views.register, name='registration'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('customer-payment/', collection.customer_payment, name='customer_payment'),
    path('customer-payment/<int:order_id>/', collection.customer_make_payment, name='customer_make_payment'),
    path('survey/<int:order_id>/', views.survey_view, name='survey_view'),
    path('survey/thank-you/', views.survey_thank_you, name='survey_thank_you'),

    # Staffs
    path('dashboard/', views.dashboard, name='dashboard'),
    path('messages/', views.cust_messages, name='messages'),
    path('send_reply_email/', views.send_reply_email, name='send_reply_email'),
    path('success/', views.success, name='success'),

    # Product
    path('create-product/', product.create_product, name='create_product'),
    path('products/', product.product_list, name='product_list'),
    path('edit-product/<int:product_id>/', product.edit_product, name='edit_product'),
    path('delete-product/<int:product_id>/', product.delete_product, name='delete_product'),

    # Order-entry
    path('create_order/', order.create_order, name='create_order'),
    path('api/customer_info/', views.customer_info, name='customer_info'),
    path('order_list', order.order_list, name='order_list'),
    path('order_detail/<int:order_id>/', order.order_detail, name='order_detail'),
    path('edit_order/<int:order_id>/', order.edit_order, name='edit_order'),
    path('delete_order/<int:order_id>/', order.delete_order, name='delete_order'),


    # Report
    path('reports/', report.report_index, name='reports'),
    path('reports/orders/', report.order_report, name='order_report'),
    path('reports/products/', report.product_report, name='product_report'),
    path('reports/products/<int:product_id>/', report.product_report, name='product_report'),
    # path('reports/customers/<int:customer_id>/', report.customer_report, name='customer_report'),
    path('reports/customers/', report.customer_report, name='customer_report'),
    path('reports/sales/', report.sales_report, name='sales_report'),
    path('reports/fulfillment/', report.fulfillment_report, name='fulfillment_report'),
    path('api/sales_data/<int:product_id>/', report.sales_data_api, name='sales_data_api'),
    path('reports/survey/', report.survey_report, name='survey_report'),
    path('reports/collections/', report.collections_report, name='collections_report'),
    path('reports/logs/', report.log_report, name='log_report'),

    # Admin
    path('customers/', customer.customer_list, name='customer_list'),
    path('customers/<int:customer_id>/', customer.customer_detail, name='customer_detail'),
    path('customers/edit/<int:customer_id>/', customer.edit_customer, name='edit_customer'),
    path('users/', customer.user_list, name='user_list'),
    path('users/<int:user_id>/manage_groups/', customer.manage_user_groups, name='manage_user_groups'),

    # Collection
    path('collections/', collection.collections_index, name='collections_index'),
    path('collections/<int:order_id>/', collection.collection_detail, name='collection_detail'),


    # Fulfillment
    path('fulfillment/', fulfillment.fulfillment_view, name='fulfillment_view'),



    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^.*$', views.not_found, name='404'),
]

merchtrack/merchtrack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchtrack/app/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.utils.timezone import now
import os

# Create your database models here.

class user_info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    student_id = models.CharField(
        max_length=9, 
        primary_key=True,  # Make student_id the primary key
        unique=True, 
        validators=[RegexValidator(r'^[0-9]{1,9}$', 'Student ID must be numeric and have at most 9 digits.')]
    )
    student_name = models.CharField(max_length=200)
    course = models.CharField(max_length=200)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.student_id

class order_info(models.Model):
    order_date = models.CharField(max_length=200)
    distribution_date = models.CharField(max_length=200)
    order_status = models.CharField(max_length=200)
    payment_method = models.CharField(max_length=200)
    payment_status = models.CharField(max_length=200)

    order_details_id = models.CharField(max_length=200, default='0')
    user_info_id  = models.CharField(max_length=9, default='000000000')
    
class order_details(models.Model):
    order_details_id = models.CharField(max_length=200)
    item_name = models.CharField(max_length=200)
    item_size = models.CharField(max_length=200)
    item_color = models.CharField(max_length=200)
    item_cost = models.CharField(max_length=200)
    item_quantity = models.CharField(max_length=200)

class contact_us(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    message = models.TextField(max_length=200)
    created_at = models.DateTimeField(default=now) 



# NEW DATA

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, default=999)
    phone = models.CharField(max_length=15)
    course = models.CharField(max_length=200)

    class Meta:
        db_table = 'customer'
        constraints = [
            models.UniqueConstraint(fields=['user'], name='unique_customer_id')
        ]
        indexes = [
            models.Index(fields=['user'], name='customer_id_idx')
        ]

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

class Product(models.Model):
    productId = models.AutoField(primary_key=True)
    productImage = models.CharField(max_length=500, blank=True, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.CharField(max_length=100)
    available = models.BooleanField(default=True)

    class Meta:
        db_table = 'product'
        constraints = [
            models.UniqueConstraint(fields=['productId'], name='unique_product_id')
        ]
        indexes = [
            models.Index(fields=['productId'], name='product_id_idx')
        ]

    def get_image(self):
        if 'drive.google.com' in self.productImage:
            file_id = self.productImage.split('/d/')[1].split('/')[0]
            return f"https://drive.google.com/thumbnail?id={file_id}&sz=w500"
        return f"https://drive.google.com/thumbnail?id={self.productImage}&sz=w500" 

    def delete(self, *args, **kwargs):
        super(Product, self).delete(*args, **kwargs)

class Order(models.Model):
    orderId = models.AutoField(primary_key=True)
    customerId = models.ForeignKey(Customer, on_delete=models.CASCADE, default=999)
    processedBy = models.ForeignKey(User, on_delete=models.CASCADE, related_name='processed_orders', default=999)
    orderDate = models.DateTimeField(default=now)
    status = models.CharField(max_length=50, default="Pending")
    totalAmount = models.FloatField(max_length=10, default=0)
    discountAmount = models.FloatField(max_length=10, default=0)
    estimatedDeliveryDate = models.DateTimeField()

    class Meta:
        db_table = 'order'
        constraints = [
            models.UniqueConstraint(fields=['orderId'], name='unique_order_id')
        ]
        indexes = [
            models.Index(fields=['orderId'], name='order_id_idx')
        ]

class OrderItem(models.Model):
    orderItemId = models.AutoField(primary_key=True)
    orderId = models.ForeignKey(Order, on_delete=models.CASCADE)
    productId = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    customerNote = models.TextField(blank=True, null=True)
    size = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        db_table = 'order_item'
        constraints = [
            models.UniqueConstraint(fields=['orderItemId'], name='unique_order_item_id')
        ]
        indexes = [
            models.Index(fields=['orderItemId'], name='order_item_id_idx')
        ]

    @property
    def total_price(self):
        return self.quantity * self.price

class Payment(models.Model):
    paymentId = models.AutoField(primary_key=True)
    orderId = models.ForeignKey(Order, on_delete=models.CASCADE)
    customerId = models.ForeignKey(Customer, on_delete=models.CASCADE, default=999)
    processedBy = models.ForeignKey(User, on_delete=models.CASCADE, related_name='processed_payments', default=999)
    paymentDate = models.DateTimeField(default=now)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    paymentMethod = models.CharField(max_length=50)
    paymentStatus = models.CharField(max_length=50, default="For Verification")
    referenceNumber = models.CharField(max_length=100, default="")

    class Meta:
        db_table = 'payment'
        constraints = [
            models.UniqueConstraint(fields=['paymentId'], name='unique_payment_id')
        ]
        indexes = [
            models.Index(fields=['paymentId'], name='payment_id_idx')
        ]

class Inventory(models.Model):
    inventoryId = models.AutoField(primary_key=True)
    productId = models.OneToOneField(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        db_table = 'inventory'
        constraints = [
            models.UniqueConstraint(fields=['inventoryId'], name='unique_inventory_id')
        ]
        indexes = [
            models.Index(fields=['inventoryId'], name='inventory_id_idx')
        ]

class Fulfillment(models.Model):
    fulfillmentId = models.AutoField(primary_key=True)
    orderId = models.OneToOneField(Order, on_delete=models.CASCADE)
    fulfillmentDate = models.DateTimeField(default=now)
    processedBy = models.ForeignKey(User, on_delete=models.CASCADE, related_name='processed_fulfillments', default=999)
    status = models.CharField(max_length=50, default="Pending")


    class Meta:
        db_table = 'fulfillment'
        constraints = [
            models.UniqueConstraint(fields=['fulfillmentId'], name='unique_fulfillment_id')
        ]
        indexes = [
            models.Index(fields=['fulfillmentId'], name='fulfillment_id_idx')
        ]

def get_default_customer():
    customer = Customer.objects.get(pk=999)
    print("Customer: ", customer)
    return customer


class Log(models.Model):
    logId = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    created_date = models.DateTimeField(default=now)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, default=999)
    reason = models.CharField(max_length=255)
    system_text = models.TextField()
    user_text = models.TextField()

    def __str__(self):
        return f"Log for {self.customer.user.username} by {self.created_by.username} on {self.created_date}"
    
    class Meta:
        db_table = 'log'
        constraints = [
            models.UniqueConstraint(fields=['logId'], name='unique_logId_id')
        ]
        indexes = [
            models.Index(fields=['logId'], name='logId_id_idx')
        ]



from django.utils import timezone

class CustomerSatisfactionSurvey(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    submit_date = models.DateTimeField(default=timezone.now)
    question1 = models.IntegerField(choices=[(1, 'Not at all'), (2, 'Somewhat'), (3, 'Very'), (4, 'Completely')])
    question2 = models.IntegerField(choices=[(1, 'Difficult'), (2, 'Neutral'), (3, 'Easy'), (4, 'Very Easy')])
    question3 = models.IntegerField(choices=[(1, 'Not at all'), (2, 'Somewhat'), (3, 'Very'), (4, 'Completely')])
    question4 = models.IntegerField(choices=[(1, 'Unlikely'), (2, 'Neutral'), (3, 'Likely'), (4, 'Very Likely')])
    comments = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'customer_satisfaction_survey'
        constraints = [
            models.UniqueConstraint(fields=['order'], name='unique_order_survey')
        ]

    def __str__(self):
        return f"Survey for Order {self.order.orderId}"

merchtrack/templates/reports/collections_report.html
{% extends 'reports/report_base.html' %}
{% block title %}Collections Report{% endblock %}
{% block content %}
{% load slippers %}

<div class="container px-4 py-8 mx-auto">
    <form method="get">
        {% csrf_token %}
        <div class='flex items-center justify-between'>
            <h1 class="mb-4 text-2xl font-bold">Collections Report</h1>
            <div class="flex items-end content-center">
                <a href="?export=excel" class="w-full align-middle btn-primary">Export to Excel</a>
            </div>
        </div>
        <table class="min-w-fit mb-6 mt-2 bg-white border border-gray-200">
            <thead class="text-left bg-gray-50">
                <tr>
                    <th class="px-4 py-2 border-b">Payment Method</th>
                    <th class="px-4 py-2 border-b">Total Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for method in total_collection_by_method %}
                <tr class="hover:bg-gray-50">
                    <td class="px-4 py-2 border-b">{{ method.paymentMethod }}</td>
                    <td class="px-4 py-2 border-b">₱{{ method.total_amount }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="grid grid-cols-1 gap-6 mb-6 md:grid-cols-3">
            <div>
                <label for="start_date" class="block mb-2 font-bold text-gray-700">Start Date</label>
                <input type="date" name="start_date" id="start_date" value="{{ start_date }}" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
            </div>
            <div>
                <label for="end_date" class="block mb-2 font-bold text-gray-700">End Date</label>
                <input type="date" name="end_date" id="end_date" value="{{ end_date }}" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
            </div>
            <div class="flex items-end">
                <button type="submit" class="self-end w-fit h-fit btn-primary">Filter</button>
            </div>
        </div>
    </form>

    <table class="min-w-full mt-4 bg-white border border-gray-200">
        <thead class="text-left bg-gray-50">
            <tr>
                <th class="px-4 py-2 border-b">Payment ID</th>
                <th class="px-4 py-2 border-b">Order ID</th>
                <th class="px-4 py-2 border-b">Customer</th>
                <th class="px-4 py-2 border-b">Processed By</th>
                <th class="px-4 py-2 border-b">Payment Date</th>
                <th class="px-4 py-2 border-b">Amount</th>
                <th class="px-4 py-2 border-b">Payment Method</th>
                <th class="px-4 py-2 border-b">Payment Status</th>
                <th class="px-4 py-2 border-b">Reference Number</th>
            </tr>
        </thead>
        <tbody>
            {% for payment in payments %}
            <tr class="hover:bg-gray-50">
                <td class="px-4 py-2 border-b">{{ payment.paymentId }}</td>
                <td class="px-4 py-2 border-b">{{ payment.orderId.orderId }}</td>
                <td class="px-4 py-2 border-b">{{ payment.customerId.user.first_name }} {{ payment.customerId.user.last_name }}</td>
                <td class="px-4 py-2 border-b">{{ payment.processedBy.first_name }} {{ payment.processedBy.last_name }}</td>
                <td class="px-4 py-2 border-b">{{ payment.paymentDate }}</td>
                <td class="px-4 py-2 border-b">₱{{ payment.amount }}</td>
                <td class="px-4 py-2 border-b">{{ payment.paymentMethod }}</td>
                <td class="px-4 py-2 border-b">{{ payment.paymentStatus }}</td>
                <td class="px-4 py-2 border-b">{{ payment.referenceNumber }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block list %}
{% for log in latest_logs %}
<li class="text-gray-700">
    <div class="flex flex-col border-b py-1">
        <p class="font-bold">{{log.reason}}</p>
        <p class="text-sm">{{log.created_by}}</p>
        <p class="text-xs text-gray-500">{{log.system_text}}</p>
        <p class="text-right text-xs text-gray-500 line-clamp-3">{{log.created_date}}</p>
    </div>
</li>
{% endfor %}
{% endblock %}

merchtrack/templates/reports/customer_report.html
{% extends 'reports/report_base.html' %}
{% block title %}Customer Report{% endblock %}
{% block content %}
{% load slippers %}



<div class="container px-4 py-8 mx-auto">
    <div class='flex justify-between'>
        <h1 class="mb-4 text-2xl font-bold">Customer Report</h1>
        <a href="{% url 'customer_report' %}?{% if selected_customer_id %}customer_id={{ selected_customer_id }}&{% endif %}{% if status %}status={{ status }}&{% endif %}export=excel" class="mb-6 btn-primary">Export to Excel</a>
    </div>
    <form method="get" class="mb-6">
    {% csrf_token %}
        <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
            <div>
                <label for="customer_id" class="block mb-2 font-bold text-gray-700">Select Customer:</label>
                <select name="customer_id" id="customer_id" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" onchange="this.form.submit()">
                    <option value="">Select a customer</option>
                    {% for customer in customers %}
                        <option value="{{ customer.user.id }}" {% if customer.user.id|stringformat:'s' == selected_customer_id %}selected{% endif %}>{{ customer }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="status" class="block mb-2 font-bold text-gray-700">Select Status:</label>
                <select name="status" id="status" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" onchange="this.form.submit()">
                    <option value="">All Statuses</option>
                    {% for s in order_statuses %}
                        <option value="{{ s }}" {% if s == status %}selected{% endif %}>{{ s }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </form>
    
    <p class='self-start'>Total Spending: {{ total_spending }}</p>
    <table class="min-w-full mt-4 bg-white border border-gray-200">
        <thead class="text-left bg-gray-50">
            <tr>
                <th class="px-4 py-2 border-b">Order ID</th>
                <th class="px-4 py-2 border-b">Username</th>
                <th class="px-4 py-2 border-b">Full Name</th>
                <th class="px-4 py-2 border-b">Date</th>
                <th class="px-4 py-2 border-b">Status</th>
                <th class="px-4 py-2 border-b">Total Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td class="px-4 py-2 border-b">{{ order.orderId }}</td>
                    <td class="px-4 py-2 border-b">{{ order.customerId.user.username }}</td>
                    <td class="px-4 py-2 border-b">{{ order.customerId.user.first_name }} {{ order.customerId.user.first_name }}</td>
                    <td class="px-4 py-2 border-b">{{ order.orderDate }}</td>
                    <td class="px-4 py-2 border-b">{{ order.status }}</td>
                    <td class="px-4 py-2 border-b">{{ order.totalAmount }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

{% block list %}
{% for log in latest_logs %}
<li class="text-gray-700">
    <div class="flex flex-col border-b py-1">
        <p class="font-bold">{{log.reason}}</p>
        <p class="text-sm">{{log.created_by}}</p>
        <p class="text-xs text-gray-500">{{log.system_text}}</p>
        <p class="text-right text-xs text-gray-500 line-clamp-3">{{log.created_date}}</p>
    </div>
</li>
{% endfor %}
{% endblock %}

merchtrack/templates/reports/fulfillment_report.html
{% extends 'reports/report_base.html' %}
{% block title %}Fulfillment Report{% endblock %}
{% block content %}
{% load slippers %}

<div class="container px-4 py-8 mx-auto">
    <form method="get">
        {% csrf_token %}
        <div class='flex items-center justify-between'>
            <h1 class="mb-4 text-2xl font-bold">Fulfillment Report</h1>
            <div class="flex items-end content-center">
                <a href="?export=excel" class="w-full align-middle btn-primary">Export to Excel</a>
            </div>
        </div>
        <div class="grid grid-cols-1 gap-6 mb-6 md:grid-cols-3">
            <div>
                <label for="start_date" class="block mb-2 font-bold text-gray-700">Start Date</label>
                <input type="date" name="start_date" id="start_date" value="{{ start_date }}" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
            </div>
            <div>
                <label for="end_date" class="block mb-2 font-bold text-gray-700">End Date</label>
                <input type="date" name="end_date" id="end_date" value="{{ end_date }}" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
            </div>
            <div class="flex items-end">
                <button type="submit" class="self-end w-fit h-fit btn-primary">Filter</button>
            </div>
        </div>
    </form>

    <table class="min-w-full mt-4 bg-white border border-gray-200">
        <thead class="text-left bg-gray-50">
            <tr>
                <th class="px-4 py-2 border-b">Fulfillment ID</th>
                <th class="px-4 py-2 border-b">Order ID</th>
                <th class="px-4 py-2 border-b">Customer</th>
                <th class="px-4 py-2 border-b">Processed By</th>
                <th class="px-4 py-2 border-b">Fulfillment Date</th>
                <th class="px-4 py-2 border-b">Estimated Delivery Date</th>
                <th class="px-4 py-2 border-b">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for fulfillment in fulfillments %}
            <tr class="hover:bg-gray-50">
                <td class="px-4 py-2 border-b">{{ fulfillment.fulfillmentId }}</td>
                <td class="px-4 py-2 border-b">{{ fulfillment.orderId.orderId }}</td>
                <td class="px-4 py-2 border-b">{{ fulfillment.orderId.customerId.user.first_name }} {{ fulfillment.orderId.customerId.user.last_name }}</td>
                <td class="px-4 py-2 border-b">{{ fulfillment.processedBy.first_name }} {{ fulfillment.processedBy.last_name }}</td>
                <td class="px-4 py-2 border-b">{{ fulfillment.fulfillmentDate }}</td>
                <td class="px-4 py-2 border-b">{{ fulfillment.orderId.estimatedDeliveryDate }}</td>
                <td class="px-4 py-2 border-b">{{ fulfillment.status }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block list %}
{% for log in latest_logs %}
<li class="text-gray-700">
    <div class="flex flex-col border-b py-1">
        <p class="font-bold">{{log.reason}}</p>
        <p class="text-sm">{{log.created_by}}</p>
        <p class="text-xs text-gray-500">{{log.system_text}}</p>
        <p class="text-right text-xs text-gray-500 line-clamp-3">{{log.created_date}}</p>
    </div>
</li>
{% endfor %}
{% endblock %}

merchtrack/templates/reports/product_report.html
{% extends 'reports/report_base.html' %}
{% block title %}Product Report{% endblock %}
{% block content %}
{% load slippers %}


<div class="container px-4 py-8 mx-auto">
    <div class='flex justify-between'>
        <h1 class="mb-4 text-2xl font-bold">Product Report</h1>
        <form method="get">
            <input type="hidden" name="product_id" value="{{ selected_product_id }}">
            <input type="hidden" name="status" value="{{ status }}">
            <button type="submit" name="export" value="excel" class="px-4 py-2 mb-4 text-white bg-blue-500 rounded">Export to Excel</button>
        </form>
    </div>
    <form method="get" class="mb-6">
        {% csrf_token %}
        <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
            <div>
                <label for="product_id" class="block mb-2 font-bold text-gray-700">Select Product:</label>
                <select name="product_id" id="product_id" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" onchange="window.location.href = '/reports/products/' + this.value + '/?status=' + document.getElementById('status').value">
                    <option value="">Select a product</option>
                    {% for product in products %}
                        <option value="{{ product.productId }}" {% if product.productId|stringformat:'s' == selected_product_id|stringformat:'s' %}selected{% endif %}>{{ product.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="status" class="block mb-2 font-bold text-gray-700">Select Status:</label>
                <select name="status" id="status" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" onchange="window.location.href = '/reports/products/{{ selected_product_id }}/?status=' + this.value">
                    <option value="">All Statuses</option>
                    {% for s in order_statuses %}
                        <option value="{{ s }}" {% if s == status %}selected{% endif %}>{{ s }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </form>
    
    <p class='self-start'>Total Quantity Sold: {{ total_quantity }}</p>
    <table class="min-w-full mt-4 bg-white border border-gray-200">
        <thead class="text-left bg-gray-50">
            <tr>
                <th class="px-4 py-2 border-b">Order ID</th>
                <th class="px-4 py-2 border-b">Customer</th>
                <th class="px-4 py-2 border-b">Date</th>
                <th class="px-4 py-2 border-b">Email</th>
                <th class="px-4 py-2 border-b">Phone</th>
                <th class="px-4 py-2 border-b">Quantity</th>
                <th class="px-4 py-2 border-b">Status</th>
                <th class="px-4 py-2 border-b">Size</th>
                <th class="px-4 py-2 border-b">Note</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                {% for item in order.orderitem_set.all %}
                    <tr>
                        <td class="px-4 py-2 border-b">{{ order.orderId }}</td>
                        <td class="px-4 py-2 border-b">{{ order.customerId.user.first_name }} {{ order.customerId.user.last_name }}</td>
                        <td class="px-4 py-2 border-b">{{ order.orderDate }}</td>
                        <td class="px-4 py-2 border-b">{{ order.customerId.user.email }}</td>
                        <td class="px-4 py-2 border-b">{{ order.customerId.phone }}</td>
                        <td class="px-4 py-2 border-b">{{ item.quantity }}</td>
                        <td class="px-4 py-2 border-b">{{ order.status }}</td>
                        <td class="px-4 py-2 border-b">{{ item.size }}</td>
                        <td class="px-4 py-2 border-b">{{ item.customerNote }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

{% block list %}
{% for log in latest_logs %}
<li class="text-gray-700">
    <div class="flex flex-col border-b py-1">
        <p class="font-bold">{{log.reason}}</p>
        <p class="text-sm">{{log.created_by}}</p>
        <p class="text-xs text-gray-500">{{log.system_text}}</p>
        <p class="text-right text-xs text-gray-500 line-clamp-3">{{log.created_date}}</p>
    </div>
</li>
{% endfor %}
{% endblock %}